### ISSUE TITLE
name is not optional

### ISSUE THREAD

**Issue by cheshire137** [127labs/generator-duxedo#19]
The README seems to say `name` is an optional parameter by having it in square brackets. When I try to use the generator without telling it a name, though, it gives an error:

```
% yo duxedo
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: Did not provide required argument name!
    at .<anonymous> (/usr/local/lib/node_modules/generator-duxedo/node_modules/yeoman-generator/lib/base.js:383:33)
    at Array.forEach (native)
    at Base.checkRequiredArgs (/usr/local/lib/node_modules/generator-duxedo/node_modules/yeoman-generator/lib/base.js:379:19)
    at argument (/usr/local/lib/node_modules/generator-duxedo/node_modules/yeoman-generator/lib/base.js:344:8)
    at new module.exports.yeoman.Base.extend.constructor (/usr/local/lib/node_modules/generator-duxedo/generators/app/index.js:11:10)
    at Environment.instantiate (/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/lib/environment.js:328:10)
    at Environment.create (/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/lib/environment.js:305:15)
    at Environment.run (/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/lib/environment.js:364:24)
    at /usr/local/l%
```

**Comment by imranismail** [comment]
Hey @cheshire137 thanks for reporting, I'll update the readme for better clarity.
